### ISSUE TITLE
Always killing comment by default

### ISSUE THREAD

**Issue by issue-dispenser** [remyferre/comment-dwim-2#3]
No matter what value I set to `comment-dwim-2--inline-comment-behavior` in my .emacs file, it will always kill the comment instead of reindenting. It does not output the error defined in `cd2/inline-comment-behavior--wrong-value` when an improper value is set.

Additionally, whenever the command `inline-comment-function` is executed, I get a warning saying `cd2/inline-comment-function: Invalid function: (quote kill-comment)`

Here is the compile log from the latest version of emacs and from MELPA:

In cd2/inline-comment-function:
comment-dwim-2.el:76:8:Warning: \`(quote kill-comment)' is a malformed function
comment-dwim-2.el:76:8:Warning: \`(quote reindent-comment)' is a malformed
    function
comment-dwim-2.el:82:25:Warning: \`t' called as a function

In cd2/prefix-function:
comment-dwim-2.el:85:8:Warning: \`(quote kill-comment)' is a malformed function
comment-dwim-2.el:85:8:Warning: \`(quote reindent-comment)' is a malformed
    function
comment-dwim-2.el:92:25:Warning: \`t' called as a function

In end of data:
comment-dwim-2.el:211:1:Warning: the following functions are not known to be
    defined: case, t

**Comment by remyferre** [comment]
Hi issue-dispenser, thanks for the bug report.

What exactly is your Emacs version? Since it is elisp issue it think it may be due some changes from Emacs (on 24.4.1 it compiles without warnings) so I need to test on your version.

**Comment by issue-dispenser** [comment]
The version is 24.5.1

**Comment by remyferre** [comment]
Can you download the new version and try again? It should work now (the bug was that `cl` was not loaded by the package)

**Comment by issue-dispenser** [comment]
Everything works fine now, thanks.
