### ISSUE TITLE
Tag version for MELPA stable

### ISSUE THREAD

**Issue by lvillani** [remyferre/comment-dwim-2#4]
Hi there,

Would you consider creating a tag (like "v1.0.0" or "1.0.0") so that MELPA stable picks it up?

Thanks!

**Comment by favadi** [comment]
:+1: for stable version.

**Comment by remyferre** [comment]
Here you go guys [http://stable.melpa.org/#/comment-dwim-2](http://stable.melpa.org/#/comment-dwim-2) !

**Comment by lvillani** [comment]
Thanks!
