### ISSUE TITLE
Avoid killing end-of-line comment when removing line comment

### ISSUE THREAD

**Issue by tmarti2** [remyferre/comment-dwim-2#7]
Hi,
first thanks for this package, really useful.

The only issue I have so far is when having something like that :
![image](https://user-images.githubusercontent.com/32908972/57532453-fc059600-733b-11e9-97d1-ecd5b9602154.png)
That's ocaml, comment are between `"(* *)"`, and you can't comment only at start of a line like `"//"` in C.
The first line is the original one, the 2nd is when commenting using `"M-;"` (comment-dwin-2) and last when uncommenting (with the same command).

My problem here is that instead of just uncommenting the line, it also remove the original comment.
Is there a way to avoid that?

Thanks

**Comment by remyferre** [comment]
hey @tmarti2, sorry for the late reply

Killing end-of-line comments is the intended behavior, but you could override that default behavior like this:

```lisp
(defun cd2/inline-comment-command () ; this is the function called when you repeat the command
  ;; do nothing (not killing the end-of-line comment)
  (setq this-command nil) ; This is just a trick so that the command can still be called indefinitely
)
```

does it solve your problem ?

**Comment by tmarti2** [comment]
It works perfectly, thanks !
