### ISSUE TITLE
in org-mode code block is Weird

### ISSUE THREAD

**Issue by yyangdid** [remyferre/comment-dwim-2#8]
create a org file
insert :
``` 
﻿#+begin_src emacs-lisp
  (+ 1 1)
  (+ 2 2)
  (+ 3 3)
  (+ 4 4)
#+end_src
```

put cursor on `(+ 4 4)`, then `M-;` or `M-; M-; M-;`

is Weird

**Comment by remyferre** [comment]
Hey,

I've released a new experimental command which should work within org-mode source code blocks.

Please update your package and add this to your init file : 
```el
    (define-key org-mode-map (kbd "M-;") 'org-comment-dwim-2)
```

**Comment by yyangdid** [comment]
It's worked, thank you very much, nice package. 👍 💯
